# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MNIST_URL": "01_matmul.ipynb",
         "get_data": "02_fully_connected.ipynb",
         "normalize": "02_fully_connected.ipynb"}

modules = ["matmul.py",
           "fully_connected.py"]

doc_url = "https://iamalos.github.io/fastai_id/"

git_url = "https://github.com/iamalos/fastai_id/tree/master/"

def custom_doc_links(name): return None
