# AUTOGENERATED! DO NOT EDIT! File to edit: 02_fully_connected.ipynb (unless otherwise specified).

__all__ = ['get_data', 'normalize']

# Cell
from .matmul import *

def get_data():
    path = datasets.download_data(MNIST_URL, ext=".gz")
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
    return map(tensor, (x_train, y_train, x_valid, y_valid))

def normalize(x, m, s): return (x-m)/s

# Cell
from torch.nn import init