# AUTOGENERATED! DO NOT EDIT! File to edit: 01_matmul.ipynb (unless otherwise specified).

__all__ = ['MNIST_URL']

# Cell
from nbdev.showdoc import *
from fastcore.test import *

from pathlib import Path
from IPython.core.debugger import set_trace
from fastai import datasets
import pickle, gzip, math, torch, matplotlib as mpl
import matplotlib.pyplot as plt
from torch import tensor

MNIST_URL = 'http://deeplearning.net/data/mnist/mnist.pkl'